[package]
name = "ruceki"
version = "0.1.0"
authors = ["Martin Huschenbett <martin.huschenbett@posteo.me>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
protobuf = "2.1.1"

[build-dependencies]
protoc-rust = "2.1.1"
