# Last edited: 2019-08-21
version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout

      - run:
          name: Install Rust tools
          command: |
              rustup component add rustfmt
              rustup component add clippy
      - restore_cache:
          name: Restore Rust cache
          keys:
              - rust-v1-{{ arch }}-{{ checksum "Cargo.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Audit and licensing
          command: |
              set -ux
              # These install commands might fail because the binaries are cached.
              cargo install cargo-audit || true
              cargo install cargo-license || true
              cargo audit
              diff <(cargo-license --do-not-bundle | sed 's/\x1b\[[0-9;]*m//g' | LC_ALL=C sort) NOTICES
      - run:
          name: Build
          command: cargo build --all --all-targets --locked
      - run:
          name: Style check
          command: cargo fmt --all -- --check
      - run:
          name: Lint
          command: cargo clippy --all --all-targets -- --deny warnings
      - run:
          name: Test
          command: cargo test --all --all-targets --locked
      - run:
          name: Benchmark
          command: cargo bench --locked
      - save_cache:
          name: Save Rust cache
          paths:
              - /usr/local/cargo/registry
              - /usr/local/cargo/bin/cargo-audit
              - /usr/local/cargo/bin/cargo-license
              - target/debug/.fingerprint
              - target/debug/build
              - target/debug/deps
              - target/releae/.fingerprint
              - target/releae/build
              - target/releae/deps
          key: rust-v1-{{ arch }}-{{ checksum "Cargo.lock" }}-{{ checksum ".circleci/config.yml" }}
